### ISSUE TITLE
Error: No yarn "build" command found

### ISSUE THREAD

**Issue by mostlyerror** [getrailsui/railsui#12]
Rails 7.0.3.4
Ruby 3.1.2

Fresh rails app, added railsui gem, bundled, and `$ rails railsui:install`

`bin/dev` fails with 
```
13:52:48 js.1   | yarn run v1.22.19
13:52:48 js.1   | error Command "build" not found.
```

**Comment by DogAndCode** [comment]
Try this @mostlyerror 

[Issue #10] (https://github.com/getrailsui/railsui/issues/10#issuecomment-1550020271)

**Comment by justalever** [comment]
After the installer runs, this should be similar to what lives in the package.json file at your project root. Notice it has the build script. I'm unsure what might have happened for it not to be present, but maybe your logs could point you to the reasoning? 

```json
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.2.1",
    "@rails/actiontext": "^7.0.4-3",
    "esbuild": "^0.17.19",
    "trix": "^2.0.4"
  },
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets"
  }
}
```

Once you install a theme, a new script is dynamically added based on the chosen framework.

**Comment by markahesketh** [comment]
This happens if your active Node.js version is below v12. I just had it while using v6.x (active from a legacy project).

```
error esbuild@0.17.19: The engine "node" is incompatible with this module. Expected version ">=12". Got "6.2.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Add build script
/usr/local/lib/node_modules/npm/lib/cli.js:66
module.exports = async process => {
                       ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npx-cli.js:3:13)
    at Module._compile (module.js:541:32)
Add "scripts": { "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets" } to your package.json
```

The generated `package.json` ends up being:

```
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.2.1",
    "@rails/actiontext": "^7.0.4-3",
    "trix": "^2.0.4"
  }
}
```

Would an `.nvmrc` help here?

**Comment by mostlyerror** [comment]
@markahesketh hmm, same failure using Node 14, i'll try latest and see

**Comment by mostlyerror** [comment]
@markahesketh got passed it using Node 18! 👍

**Comment by justalever** [comment]
Ok, cool, this is related to node/yarn. I went ahead and added a `.nvmrc` file and updated the installation section of the readme.
