### ISSUE TITLE
uninitialized constant Railsui::MailHelper exception when setting up mailing in dev or prod

### ISSUE THREAD

**Issue by augustosamame** [getrailsui/railsui#40]
Hello. Been using RailsUI without a hitch in my latest project. Congrats on a great new gem and concept

Rails 7.2.1
Ruby 3.3.4
RailsUI 2.1.1

However, trying to set up email in development or production will trigger this error when starting rails server: 

```
rails s -e production -p 5000
=> Booting Puma
=> Rails 7.2.1 application starting in production
=> Run `bin/rails server --help` for more startup options
Exiting
/Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/bundler/gems/railsui-8d80d6ebd2f2/lib/railsui/engine.rb:32:in `block (2 levels) in <class:Engine>': uninitialized constant Railsui::MailHelper (NameError)

          helper Railsui::MailHelper
```

I have reproduced this with a brand new Rails project with only RailsUI as a dependency, ran the RailsUI installer and everything works fine. But as soon as I add to dev or prod environment files: 

```
config.action_mailer.default_url_options = { :host => 'mydomain.com' }

  config.action_mailer.delivery_method = :smtp
  ActionMailer::Base.smtp_settings =
  {
    :address            => 'email-smtp.us-east-1.amazonaws.com',
    :port               => 587,
    :domain             => 'mydomain.com,
    :authentication     => :login,
    :user_name          => ENV['SES_SMTP_USER'],
    :password           => ENV['SES_SMTP_PASSWORD'],
    #:ssl                => true,
    #:tls                => true,
    :openssl_verify_mode => "peer",
    :enable_starttls_auto => true
  }
```

then rails server errors out as indicated above

I have uploaded my sample project reproducing the error here:  

https://github.com/augustosamame/sample_railsui_bug

complete stack trace follows. Checked the RailsUI and the helper is right there, so no idea what's going on, and the error is only triggered when action_mailer config is updated with real values.

 ```
/Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/bundler/gems/railsui-8d80d6ebd2f2/lib/railsui/engine.rb:32:in `block (2 levels) in <class:Engine>': uninitialized constant Railsui::MailHelper (NameError)

          helper Railsui::MailHelper
                        ^^^^^^^^^^^^
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:62:in `block in on_load'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:61:in `each'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:61:in `on_load'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/bundler/gems/railsui-8d80d6ebd2f2/lib/railsui/engine.rb:31:in `block in <class:Engine>'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/initializable.rb:32:in `run'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/augusto/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
	from /Users/augusto/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
	from /Users/augusto/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
	from /Users/augusto/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
	from /Users/augusto/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `each'
	from /Users/augusto/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `call'
	from /Users/augusto/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
	from /Users/augusto/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
	from /Users/augusto/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/application.rb:435:in `initialize!'
	from /Users/augusto/workspace/devtech/sample_tailwind/config/environment.rb:5:in `<main>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block (2 levels) in <main>'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/rack-3.1.7/lib/rack/builder.rb:108:in `eval'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/rack-3.1.7/lib/rack/builder.rb:108:in `new_from_string'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/rack-3.1.7/lib/rack/builder.rb:97:in `load_file'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/rack-3.1.7/lib/rack/builder.rb:67:in `parse_file'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/rackup-2.1.0/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/rackup-2.1.0/lib/rackup/server.rb:263:in `app'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/rackup-2.1.0/lib/rackup/server.rb:424:in `wrapped_app'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/rackup-2.1.0/lib/rackup/server.rb:326:in `block in start'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/rackup-2.1.0/lib/rackup/server.rb:382:in `handle_profiling'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/rackup-2.1.0/lib/rackup/server.rb:325:in `start'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/commands/server/server_command.rb:38:in `start'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/commands/server/server_command.rb:136:in `perform'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/command/base.rb:73:in `perform'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/command.rb:71:in `block in invoke'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/command.rb:149:in `with_argv'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/command.rb:69:in `invoke'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/railties-7.2.1/lib/rails/commands.rb:18:in `<main>'
	from /Users/augusto/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/augusto/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/augusto/.rvm/gems/ruby-3.3.4@sample_tailwind/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'

```

**Comment by justalever** [comment]
Thanks for posting this issue, @augustosamame. I just [pushed an update](https://github.com/getrailsui/railsui/commit/1db7480fd26d2d3e1be423f608f851e4b0f6b08a) to hopefully address this, but report back if this doesn't solve it. You'll need to update the gem from the main branch.

**Comment by augustosamame** [comment]
Thanks for the prompt response. But unfortunately, the update did not fix the issue. I did make sure to bundle clean --force and redownload the gem and checked that the new downloaded gem had this changed line locally before testing:

```

initializer "railsui.mailer_helper" do
        ActiveSupport.on_load :action_mailer do
          helper Railsui::MailHelper
        end
      end
```

**Comment by justalever** [comment]
Got it. Will inspect this further and report back!

**Comment by augustosamame** [comment]
I have created a PR that fixed the issue for me in my forked version

**Comment by justalever** [comment]
Thanks for that! I just shipped an updated version, removing the need for the extra helper.
